### ISSUE TITLE
how do i use it?

### ISSUE THREAD

**Issue by GauravM512** [yazninja/wuwa-tweaks#6]
![image](https://github.com/yazninja/wuwa-tweaks/assets/37218716/17806011-0eae-42c0-8707-0a0bb1f30b34)

**Comment by yazninja** [comment]
Hi, currently im having problems with the build system as it does not invlude the library to open the file dialog, tomorrow ill be pushing an update that should sort that out

**Comment by yazninja** [comment]
> ![image](https://private-user-images.githubusercontent.com/7613901/337377467-acf0a689-1194-49bf-aafc-7406952e7f1d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc3NDE0ODAsIm5iZiI6MTcxNzc0MTE4MCwicGF0aCI6Ii83NjEzOTAxLzMzNzM3NzQ2Ny1hY2YwYTY4OS0xMTk0LTQ5YmYtYWFmYy03NDA2OTUyZTdmMWQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MDdUMDYxOTQwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzRlN2Y3YWIxYWZlODEzNTZmNjdjOGJkMjc2ZWFkOWZmNzNhNDJlYjQyYTgzZWE1NTRhOGE5MWY1MzdmZWYxYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.SQEnRLoR1EGarze9t9_WFkQWWkbWk6xBkUK55ipGAQk) new update

Check the path you have inputted, the case for you might need to be `C:\Wuthering Waves Game\Wuthering Waves.exe`

**Comment by yazninja** [comment]
@spix18 I also added your install folder to the automatic search path, downloading the new update should work :). Sorry for the inconvenience.

@GauravM512 try the new release as well.

**Comment by GauravM512** [comment]
@yazninja New release is working flawless.
Thank you! <3
